### ISSUE TITLE
Date picker calenders not limited to date range extent for non-ncWMS layers

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#1784]
## Problem 
The DateFilterPanel.js _setMinMax is never being utilised.
Dates in the calender picker should be limited to the extent of the data

## Solution
A Geoserver service is needed that can supply the data Min and Max date range.

**Comment by dnahodil** [comment]
Can I suggest we leave this until after the time filter has been 'globalised'?

The required behaviour will change at that point (all time ranges will need to be taken into account) and it's probably not worth fixing it twice.

**Comment by dnahodil** [comment]
Ming at TPAC (@fxmzb123) has spotted this issue and it is causing them problems. If the accordion work has been pushed-back then we probably should fix this sooner. (I've re-added the 'bug' label accordingly).

I think the problem comes from https://github.com/aodn/aodn-portal/blob/442355c1318504dba3e272fcdd4c9064e0a6d383/web-app/js/portal/filter/ui/DateFilterPanel.js#L32, it isn't looking in the right place to find the possible values.

It's worth noting that TPAC have datasets which project into the future so both the from- and to- dates need to support dates in the future.

**Comment by pblain** [comment]
Already in backlog: https://github.com/aodn/backlog/issues/62

**Comment by smancini** [comment]
This issue is still valid as it refers to non-ncWMS layer.

For ncWMS layer, dates in the calendar picker are updated and only show availalbe dates.

It is still not the case for non-ncWMS layers like for example Argo.

**Comment by pblain** [comment]
it's in aodn/backlog#62

**Comment by smancini** [comment]
Yes but aodn/backlog#62 is closed
Should it be reopened?
